vpc_cidr_block             = "10.0.0.0/16"
public_subnet_cidr_block   = "10.0.1.0/24"
private_subnet_cidr_block  = "10.0.2.0/24"
availability_zone          = "us-east-2a"
bucket_name                = "terraform-state-bucketxyz123"
cluster_name               = "eks-cluster"
